import {StyleSheet, Dimensions} from 'react-native';
import Constants from '../../Helpers/constant';
const styles = StyleSheet.create({
  headerTitle: {
    color: Constants.white,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  container: {
    flex: 1,
    backgroundColor: Constants.black,
    paddingHorizontal: 20,
  },
  pageTitle: {
    color: Constants.white,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  postjobView: {
    marginTop: 20,
    height: 85,
    backgroundColor: Constants.grey,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postjobText: {
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 30,
    color: Constants.red,
  },
  postjobView2: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingVertical: 15,
    paddingLeft: 15,
    marginVertical: 10,
    position: 'relative',
  },
  postjobView3: {
    // borderWidth: 2,
    // borderColor: Constants.grey,
    // borderRadius: 15,
    // padding: 20,
    marginVertical: 15,
    position: 'relative',
  },

  selectjobname: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingleft: 15,
    marginBottom: 15,
    justifyContent: 'center',
  },
  postjobtitle: {
    color: Constants.white,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    fontSize: 14,
    // marginLeft: 10,
    lineHeight: 18,
  },
  postjobTitleView: {
    flex: 4,
    justifyContent: 'center',
    borderRightColor: Constants.red,
    borderRightWidth: 2,
  },
  showdetail: {
    color: Constants.red,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  iconView: {
    position: 'absolute',
    right: 15,
    bottom: -13,
    borderColor: Constants.lightgrey,
    borderWidth: 2,
    borderRadius: 15,
    height: 28,
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Constants.black,
  },
  showAmount: {
    color: Constants.red,
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  description: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Helvetica',
    color: Constants.white,
    lineHeight: 15,
    marginTop: 5,
  },
  applyBtn: {
    backgroundColor: Constants.red,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    width: '90%',
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  applyBtn1: {
    backgroundColor: Constants.green,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    width: '90%',
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  applyBtnTxt: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 16,

    lineHeight: 18,
  },
  amountTimeMainView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    color: Constants.lightgrey,
  },
  amountTime: {
    color: Constants.white,
    fontWeight: '600',
    fontFamily: 'Helvetica',
    fontSize: 13,
    marginLeft: 5,
    lineHeight: 18,
  },

  jobUpdatbtn: {
    backgroundColor: Constants.red,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  jobUpdatBtnTxt: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 22,
  },

  labelStyle: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 14,
  },
  editjobinput: {
    height: 15,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    margin: 0,
    lineHeight: 12,
    marginLeft: 2,
    color: Constants.lightgrey,
  },

  editjobDesc: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    margin: 0,
    // lineHeight: 12,
    marginLeft: 2,
    flexWrap: 'wrap',
  },

  jobname: {
    color: Constants.red,
    marginLeft: 10,
  },
  fieldView2: {
    backgroundColor: Constants.grey,
    width: Dimensions.get('window').width - 40,
    height: 60,
    marginTop: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    // paddingVertical: 5,
  },
  iconView2: {
    height: 45,
    width: 70,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 4,
    borderRightColor: Constants.red,
  },
  // icon: {
  //   height: 25,
  //   width: 18,
  // },
  input2: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    color: Constants.white,
  },
  filterView: {
    flexDirection: 'row',
    marginVertical: 20,
  },
  listtypeName: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    color: Constants.white,
  },
  jobId: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  avtarView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileInputView: {
    borderColor: Constants.grey,
    borderWidth: 1,
    borderRadius: 15,
    paddingVertical: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    marginTop: 15,
  },
  inputLabel: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  profileInput: {
    flex: 1,
    height: 20,
    color: Constants.white,
    marginLeft: 20,
    padding: 0,
    fontSize: 16,
  },
  profileInput2: {
    flex: 1,
    color: Constants.white,
    marginLeft: 20,
    padding: 0,
    fontSize: 16,
  },
  list: {
    marginVertical: 10,
    // marginHorizontal: 20,
    borderColor: Constants.grey,
    borderWidth: 1,
    borderRadius: 5,
    // padding: 10,
  },
  item: {
    // padding: 10,
    fontSize: 16,
    height: 'auto',
    marginVertical: 5,
    // borderBottomWidth: 1,
    // borderBottomColor: 'lightgrey',
    fontFamily: 'Mulish-SemiBold',
    width: Dimensions.get('window').width - 100,
    flexWrap: 'wrap',
    color: Constants.red,
  },
  validateBorder: {
    borderBottomColor: Constants.red,
    borderBottomWidth: 1,
    paddingBottom: 5,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  uploadIdView: {
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadId: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 30,
    opacity: 0.3,
  },
  editprofilebtnView: {
    paddingVertical: 5,
    // paddingHorizontal: 20,
    borderColor: Constants.red,
    borderWidth: 2,
    borderRadius: 20,
    width: 100,
  },
  editprofilebtnText: {
    color: Constants.white,
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    textAlign: 'center',
  },
  settingsView: {
    borderWidth: 1,
    borderColor: Constants.grey,
    // height: 55,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: 20,
  },

  // ----------------------------------------
  notificationSetingView: {
    borderWidth: 1,
    borderColor: Constants.grey,
    marginTop: 20,
    borderRadius: 15,
  },
  notificationtitle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },

  pushNoti: {
    flex: 3,
  },
  pushNotiView: {
    flexDirection: 'row',
    alignContent: 'center',
    margin: 10,
  },
  fieldView: {
    backgroundColor: Constants.grey,
    width: Dimensions.get('window').width - 80,
    height: 50,
    marginTop: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },

  input: {
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    color: Constants.red,
    flex: 1,
  },

  // ====================================================

  settingstext: {
    color: Constants.white,
    marginHorizontal: 15,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  icon: {
    height: 25,
    width: 25,
  },
  updatecardView: {
    marginTop: 20,
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingHorizontal: 20,
  },
  updatecardInput: {
    height: 35,
    borderRadius: 10,
    backgroundColor: Constants.grey,
    marginTop: 10,
    marginLeft: 20,
    padding: 0,
    paddingHorizontal: 10,
    color: Constants.white,
  },

  reviewAvatar: {
    justifyContent: 'center',
    alignItems: 'center',
  },

  // --------------------------------------logout modal----------------------------------
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: '#rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  textStyle: {
    color: Constants.black,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  modalText: {
    color: Constants.white,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 14,
  },
  cancelAndLogoutButtonWrapStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  cancelButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.black,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginRight: 15,
  },
  logOutButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.red,
    borderRadius: 5,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
  },

  // ---------------------------------------------------

  pound: {
    fontSize: 16,
    color: Constants.black,
    backgroundColor: Constants.red,
    width: 25,
    height: 25,
    borderRadius: 100,
    textAlign: 'center',
    fontWeight: 'bold',
  },
});

export default styles;
