/* eslint-disable no-dupe-keys */
// eslint-disable-next-line prettier/prettier
import { StyleSheet, Dimensions } from 'react-native';
import Constants from '../../Helpers/constant';
const styles = StyleSheet.create({
  red: {
    color: Constants.red,
  },
  headerTitle: {
    color: Constants.white,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  container: {
    flex: 1,
    backgroundColor: Constants.black,
    paddingHorizontal: 20,
  },
  fieldView: {
    backgroundColor: Constants.grey,
    width: Dimensions.get('window').width - 40,
    height: 60,
    marginTop: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
    // paddingVertical: 5,
  },
  fieldView: {
    backgroundColor: Constants.grey,
    width: Dimensions.get('window').width - 80,
    height: 50,
    marginTop: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  iconView: {
    height: 45,
    width: 70,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 4,
    borderRightColor: Constants.red,
  },
  iconView2: {
    position: 'absolute',
    right: 15,
    bottom: -13,
    borderColor: Constants.lightgrey,
    borderWidth: 2,
    borderRadius: 15,
    height: 28,
    width: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Constants.black,
    flex: 1,
  },
  icon: {
    height: 25,
    width: 18,
  },
  input: {
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    color: Constants.white,
  },
  input2: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    color: Constants.white,
    width: Dimensions.get('window').width,
  },
  title: {
    color: Constants.red,
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },

  switchView: {
    flexDirection: 'row',
    // marginTop: 20,
    // width: Dimensions.get('window').width - 40,
    position: 'relative',
    alignItems: 'center',
  },

  switchView2: {
    width: 40,
    borderRadius: 15,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },

  filterBtn: {
    height: 45,
    paddingHorizontal: 20,
    marginVertical: 20,
    backgroundColor: Constants.grey,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  filterBtnTxt: {
    fontSize: 14,
    color: Constants.white,
    fontWeight: '400',
    fontFamily: 'Helvetica',
  },

  livejobView: {
    borderWidth: 1,
    borderColor: Constants.lightgrey,
    // borderRadius: 15,
    padding: 20,
    marginVertical: 20,
    position: 'relative',
    minHeight: 180,
    borderTopWidth: 4,
    borderTopColor: Constants.red,
  },
  livejobView2: {
    borderWidth: 2,
    borderColor: Constants.red,
    borderRadius: 15,
    padding: 15,
  },
  jobtitle: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 20,
    textAlign: 'center',
    // backgroundColor: Constants.red,
  },
  jobStatus: {
    marginTop: 15,
    // borderColor: Constants.green,
    // borderWidth: 2,
    // borderRadius: 15,
    width: 180,
    justifyContent: 'space-around',
  },

  bookingHeaderNumber: {
    color: Constants.red,
    fontSize: 22,
    // fontFamily: Constants.font700,
    fontWeight: '700',
  },

  bookingHeaderNumberView: {
    // color: Constants.white,
    // borderColor: Constants.white,
    // borderWidth: 2,
    height: 80,
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 42,
    paddingBottom: 2,
    // marginLeft: 20,
    backgroundColor: Constants.newBlack,
  },

  jobStatustext: {
    color: Constants.green,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 30,
    textAlign: 'center',
    paddingVertical: 5,
  },
  amountTimeMainView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // amountTime: {
  //   color: Constants.white,
  //   fontWeight: '700',
  //   fontFamily: 'Helvetica',
  //   fontSize: 12,
  //   marginLeft: 10,
  //   lineHeight: 18,
  // },
  mylivejobtitle: {
    position: 'absolute',
    top: -17,
    // left: 20,
    backgroundColor: Constants.black,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 5,
  },
  reportbtn: {
    position: 'absolute',
    bottom: -10,
    right: 20,
    zIndex: 100,
    backgroundColor: Constants.black,
    paddingHorizontal: 5,
  },

  availablejobtitle: {
    color: Constants.white,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    fontSize: 18,
    marginLeft: 10,
    lineHeight: 18,
  },
  // applyBtn: {
  //   backgroundColor: Constants.red,
  //   height: 30,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 5,
  //   width: 90,
  // },
  applyBtn: {
    backgroundColor: Constants.red,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    width: '90%',
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  applyBtnTxt: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 12,

    lineHeight: 18,
  },

  postjobView2: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingVertical: 15,
    paddingLeft: 20,
    marginVertical: 15,
    position: 'relative',
  },
  postjobView3: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    padding: 20,
    marginVertical: 15,
    position: 'relative',
  },
  postjobTitleView: {
    flex: 4,
    justifyContent: 'center',
    borderRightColor: Constants.red,
    borderRightWidth: 2,
  },
  postjobtitle: {
    color: Constants.white,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    fontSize: 14,
    // marginLeft: 10,
    lineHeight: 18,
  },

  amountTimeMainView2: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  amountTime: {
    color: Constants.white,
    fontWeight: '600',
    fontFamily: 'Helvetica',
    fontSize: 12,
    marginLeft: 10,
    lineHeight: 18,
  },
  showAmount: {
    color: Constants.red,
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  description: {
    fontSize: 11,
    fontWeight: '500',
    fontFamily: 'Helvetica',
    color: Constants.white,
    lineHeight: 15,
    marginTop: 5,
  },
  listtypeName: {
    fontSize: 20,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    color: Constants.white,
  },
  filterView: {
    flexDirection: 'row',
    marginVertical: 20,
    // flex: 1,
  },
  settingsView: {
    borderWidth: 1,
    borderColor: Constants.grey,
    // height: 55,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: 20,
  },
  settingstext: {
    color: Constants.white,
    marginHorizontal: 15,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  icon2: {
    height: 25,
    width: 25,
  },
  mapView: {
    marginVertical: 20,
    borderBottomStartRadius: 15,
    borderBottomEndRadius: 15,
    borderRadius: 15,
    overflow: 'hidden',
  },
  mapheader: {
    flexDirection: 'row',
    paddingVertical: 20,
    paddingHorizontal: 30,
    backgroundColor: Constants.grey,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    alignItems: 'center',
  },
  mapheadertxt: {
    color: Constants.white,
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },
  mapheadertxt2: {
    color: Constants.red,
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    marginLeft: 10,
  },
  jobId: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  selectjobname: {
    borderWidth: 2,
    borderColor: Constants.grey,
    borderRadius: 15,
    paddingleft: 15,
    marginBottom: 15,
    justifyContent: 'center',
  },
  mileCount: {
    color: Constants.red,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    marginHorizontal: 10,
  },
  avtarView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  profileInputView: {
    borderColor: Constants.grey,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    marginTop: 15,
  },
  inputLabel: {
    color: Constants.red,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  profileInput: {
    flex: 1,
    height: 20,
    color: Constants.white,
    marginLeft: 20,
    padding: 0,
    fontSize: 16,
  },
  profileInput2: {
    flex: 1,
    color: Constants.white,
    marginLeft: 20,
    padding: 0,
    fontSize: 16,
  },
  editprofilebtnView: {
    paddingVertical: 5,
    // paddingHorizontal: 20,
    borderColor: Constants.red,
    borderWidth: 2,
    borderRadius: 20,
    width: 100,
  },
  editprofilebtnText: {
    color: Constants.white,
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    textAlign: 'center',
  },

  notificationSetingView: {
    borderWidth: 1,
    borderColor: Constants.grey,
    marginTop: 20,
    borderRadius: 15,
  },
  notificationtitle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },

  pushNoti: {
    flex: 2,
  },
  pushNotiView: {
    flexDirection: 'row',
    alignContent: 'center',
    margin: 10,
  },

  jobUpdatbtn: {
    backgroundColor: Constants.red,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },
  jobUpdatBtnTxt: {
    color: Constants.white,
    fontWeight: '700',
    fontFamily: 'Helvetica',
    fontSize: 22,
  },

  input: {
    marginLeft: 10,
    fontSize: 15,
    fontWeight: '400',
    fontFamily: 'Helvetica',
    color: Constants.red,
    flex: 1,
  },

  applyBtn1: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: Constants.red,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    // width: 50,
    borderColor: 'rgba(51, 51, 51, 0.6)',
    borderWidth: 3,
  },

  // --------------------------------------logout modal----------------------------------
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: '#rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  textStyle: {
    color: Constants.black,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 16,
  },
  modalText: {
    color: Constants.white,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 14,
  },
  cancelAndLogoutButtonWrapStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  cancelButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.black,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginRight: 15,
  },
  logOutButtonStyle: {
    flex: 0.5,
    backgroundColor: Constants.red,
    borderRadius: 5,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
  },
  showdetail: {
    color: Constants.red,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Helvetica',
  },

  // ---------------------------------------------------

  pound: {
    fontSize: 16,
    color: Constants.black,
    backgroundColor: Constants.red,
    width: 25,
    height: 25,
    borderRadius: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },

  ///suspend model///
  centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      // marginTop: 22,
      backgroundColor: '#rgba(0, 0, 0, 0.5)',
    },
    modalView: {
      margin: 17,
      backgroundColor: 'white',
      borderRadius: 10,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
      position: 'relative',
    },
  
    textStyle5: {
      color: Constants.black,
      textAlign: 'center',
      fontFamily: 'Helvetica',
      fontWeight: '800',
      fontSize: 18,
      marginRight:-35
    },
    textStyle4: {
      color: Constants.customgrey2,
      textAlign: 'center',
      fontFamily: 'Helvetica',
      fontWeight: '600',
      fontSize: 14,
      marginTop:10
    },
    modalText: {
      color: Constants.white,
      // fontWeight: 'bold',
      textAlign: 'center',
      fontFamily: 'Helvetica',
      fontWeight: '700',
      fontSize: 16,
    },
    logOutButtonStyle2: {
      backgroundColor: Constants.red,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      height:45,
      width:250,
      marginTop:20
    },
     croscov:{
      padding:7,
      borderRadius:40,
      borderWidth:1,
      borderColor:Constants.red
    },
    covline: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
});

export default styles;
